apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui@{{ .Values.digest }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            # TODO: Try to create several using URLS and URLS_PRIMARY_NAME, but I'd need another model
            - name: URL
              value: /{{.Values.rootApiPath}}/{{ .Values.main.name }}/{{ .Values.main.file }}
          volumeMounts:
            - name: apis
              mountPath: /usr/share/nginx/html/{{ .Values.rootApiPath }}
              readOnly: true
        {{- range .Values.apis }}
        - name: git-sync-{{ .name }}
          image: "k8s.gcr.io/git-sync:v{{ $.Values.gitSync.version }}"
          volumeMounts:
            - name: apis
              mountPath: /{{ $.Values.rootApiPath }}
          env:
            - name: GIT_SYNC_WAIT
              value: {{ $.Values.gitSync.refreshPeriod | quote }}
            - name: GIT_SYNC_REPO
              value: {{ .repo }}
            - name: GIT_SYNC_BRANCH
              value: {{ .branch }}
            - name: GIT_SYNC_DEST
              value: {{ .name }}
            - name: GIT_SYNC_ROOT
              value: /{{ $.Values.rootApiPath }}
          lifecycle:
            postStart:
              exec:
                command: 
                  - "sh"
                  - "-c"
                  - | 
                    until [ -e /{{ $.Values.rootApiPath }}/{{ .name }} ]; do 
                      sleep 1
                    done
        {{- end }}
      volumes:
        - name: apis
          emptyDir: {}
